scheme_version: 1
token: token
os:
  password: rancher
  dns_nameservers:
  - 1.1.1.1
install:
  mode: create
  management_interface:
    interfaces:
      - name: ens18
    default_route: true
    method: dhcp
    bond_options:
      mode: balance-tlb
      miimon: 100
  device: /dev/sda
  iso_url: http://192.168.0.182/iso/harvester-v1.2.1-amd64.iso
  vip: 203.0.113.180
  vip_mode: static
