scheme_version: 1
token: token
os:
  server_url: https://203.0.113.180:443
  password: harvester
  dns_nameservers:
  - 1.1.1.1
install:
  mode: join
  management_interface:
    interfaces:
      - name: ens18
    default_route: true
    method: dhcp
    bond_options:
      mode: balance-tlb
      miimon: 100
  device: /dev/sda
  iso_url: http://192.168.0.182/iso/harvester-v1.2.1-amd64.iso
